// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  var AboutCtrl;

  AboutCtrl = (function() {
    function AboutCtrl() {
      this.awesomeThings = ['HTML5 Boilerplate', 'AngularJS', 'Karma'];
    }

    return AboutCtrl;

  })();

  angular.module('todoApp').controller('AboutCtrl', AboutCtrl);

}).call(this);

//# sourceMappingURL=about.js.map
