// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';

  /**
   * @ngdoc function
   * @name todoApp.controller:AboutCtrl
   * @description
   * # AboutCtrl
   * Controller of the todoApp
   */
  var AuthCtrl;

  AuthCtrl = (function() {
    function AuthCtrl($scope, $rootScope, Storage, $timeout, $log, AccessToken, EndpointConfigService) {
      var storage_token;
      this.$scope = $scope;
      this.$rootScope = $rootScope;
      this.Storage = Storage;
      this.$timeout = $timeout;
      this.$log = $log;
      this.AccessToken = AccessToken;
      this.EndpointConfigService = EndpointConfigService;
      this.site = this.EndpointConfigService.getUrl('');
      this.profile_url = this.EndpointConfigService.getUrl('/me');
      storage_token = this.Storage.get('token');
      if (storage_token) {
        this.$scope.accessToken = storage_token.access_token;
      }
      this.$scope.$on('oauth:expired', (function(_this) {
        return function(event) {
          _this.$rootScope.accessToken = null;
          _this.$scope.accessToken = null;
        };
      })(this));
      this.$scope.$on('oauth:login', (function(_this) {
        return function(event, token) {
          _this.$rootScope.accessToken = token.access_token;
          _this.$scope.accessToken = token.access_token;
        };
      })(this));
      this.$scope.$on('oauth:logout', (function(_this) {
        return function(event) {
          _this.$rootScope.accessToken = null;
          _this.$scope.accessToken = null;
        };
      })(this));
    }

    return AuthCtrl;

  })();

  AuthCtrl.$inject = ['$scope', '$rootScope', 'Storage', '$timeout', '$log', 'AccessToken', 'EndpointConfigService'];

  angular.module('todoApp').controller('AuthCtrl', AuthCtrl);

}).call(this);

//# sourceMappingURL=auth.js.map
