// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  var MainCtrl;

  MainCtrl = (function() {
    function MainCtrl() {
      this.awesomeThings = ['HTML5 Boilerplate', 'AngularJS', 'Karma'];
    }

    return MainCtrl;

  })();

  angular.module('todoApp').controller('MainCtrl', MainCtrl);

}).call(this);

//# sourceMappingURL=main.js.map
