// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  var NavCtrl;

  NavCtrl = (function() {
    function NavCtrl($scope, Storage) {
      this.$scope = $scope;
      this.Storage = Storage;
      this.foo = "bar";
    }

    NavCtrl.prototype.isLoggedIn = function() {
      var storage_token;
      storage_token = this.Storage.get('token');
      if (storage_token) {
        if (storage_token.access_token) {
          return true;
        }
      } else {
        return false;
      }
    };

    return NavCtrl;

  })();

  NavCtrl.$inject = ['$scope', 'Storage'];

  angular.module('todoApp').controller('NavCtrl', NavCtrl);

}).call(this);

//# sourceMappingURL=nav.js.map
