// Generated by CoffeeScript 1.10.0
(function() {
  var TodoCtrl;

  TodoCtrl = (function() {
    function TodoCtrl($scope, TodoService) {
      this.$scope = $scope;
      this.TodoService = TodoService;
      this.todos = [];
      this.getTodos();
      this.$scope.todoSortable = {
        containment: 'parent',
        cursor: 'move',
        tolerance: 'pointer'
      };
    }

    TodoCtrl.prototype.getTodos = function() {
      return this.TodoService.all().then((function(_this) {
        return function(result) {
          return _this.todos = result.data.todos;
        };
      })(this));
    };

    TodoCtrl.prototype.addTodo = function() {
      return this.TodoService.create({
        "title": this.todoText,
        "done": false
      }).then((function(_this) {
        return function(result) {
          _this.todoText = '';
          return _this.getTodos();
        };
      })(this));
    };

    TodoCtrl.prototype.remaining = function() {
      return this.TodoService.getRemaining();
    };

    TodoCtrl.prototype.archive = function() {
      return this.todos = this.TodoService.archive().then((function(_this) {
        return function(result) {
          return _this.todos = result.data.todos;
        };
      })(this));
    };

    TodoCtrl.prototype.updateTodo = function(obj) {
      return this.TodoService.update(obj).then((function(_this) {
        return function(result) {
          return _this.getTodos();
        };
      })(this));
    };

    return TodoCtrl;

  })();

  TodoCtrl.$inject = ['$scope', 'TodoService'];

  angular.module('todoApp').controller('TodoCtrl', TodoCtrl);

}).call(this);

//# sourceMappingURL=todo.js.map
