"""empty message

Revision ID: 23b1ca85d37c
Revises: 34dc0d592268
Create Date: 2016-01-28 11:50:02.113891

"""

# revision identifiers, used by Alembic.
revision = '23b1ca85d37c'
down_revision = '34dc0d592268'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_login_ip', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'current_login_ip')
    ### end Alembic commands ###
