"""empty message

Revision ID: 2bd2b430f3a3
Revises: 23b1ca85d37c
Create Date: 2016-01-28 11:50:29.044472

"""

# revision identifiers, used by Alembic.
revision = '2bd2b430f3a3'
down_revision = '23b1ca85d37c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login_count', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'login_count')
    ### end Alembic commands ###
