info:
  title: Todo API
  description: Todo API 서버입니다
  termsOfService: http://swagger.io/terms
  version: "0.1"
  contact:
    email: yoophi@gmail.com
host: localhost:5000
basePath: /api/v1.0
schemes:
  - http
produces:
  - application/json
tags:
  - name: todo
    description: Everything about your Todos
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
  - name: user
    description: Operations about user
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
definitions:
  Todo:
    type: object
    required:
      - title
      - is_completed
    properties:
      id:
        type: integer
      title:
        type: string
      is_completed:
        type: boolean
        default: false
      _links:
        type: object
        properties:
          collection:
            type: string
          self:
            type: string
  User:
    type: object
    properties:
      id:
        type: integer
        format: int64
      email:
        type: string
securityDefinitions:
  petstore_auth:
    type: oauth2
    authorizationUrl: http://localhost:5000/api/v1.0/oauth/authorize
    flow: implicit
    scopes:
      email: User 및 Todo 에 대한 기본 작업에 대한 권한
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
